/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todolisttry2;

import java.awt.Font;

/**
 *
 * @author anime
 */
public class AddSubtaskForm extends javax.swing.JFrame {

    MainController mainContr;
    String subtaskName;
    String taskName;
    /**
     * Creates new form AddSubtaskForm
     * @param taskName
     * @param mainContr
     */
    public AddSubtaskForm(String taskName, MainController mainContr) {
        initComponents();
        
        this.mainContr = mainContr;
        this.taskName = taskName;
        
        this.setTitle("Добавление задачи");
        this.setLocation(200, 150);
        this.setVisible(true);
        
        addSubtaskButton.setFont(new Font("Arial", Font.BOLD, 12));    //установка шрифтов
        cancelFormButton.setFont(new Font("Arial", Font.BOLD, 12)); //установка шрифтов
        enterNameLabel.setFont(new Font("Arial", Font.BOLD, 12));  //установка шрифтов
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterNameLabel = new javax.swing.JLabel();
        subtaskNameField = new javax.swing.JTextField();
        addSubtaskButton = new javax.swing.JButton();
        cancelFormButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterNameLabel.setText("Введите текст подзадачи");

        subtaskNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        addSubtaskButton.setText("Принять");
        addSubtaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubtaskButtonActionPerformed(evt);
            }
        });

        cancelFormButton.setText("Закрыть");
        cancelFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(subtaskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSubtaskButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelFormButton)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(enterNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subtaskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSubtaskButton)
                    .addComponent(cancelFormButton))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSubtaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubtaskButtonActionPerformed
        subtaskName = subtaskNameField.getText();
        mainContr.addSubtask(subtaskName, taskName, false);
        this.dispose();
    }//GEN-LAST:event_addSubtaskButtonActionPerformed

    private void cancelFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFormButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelFormButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubtaskButton;
    private javax.swing.JButton cancelFormButton;
    private javax.swing.JLabel enterNameLabel;
    private javax.swing.JTextField subtaskNameField;
    // End of variables declaration//GEN-END:variables
}
