/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todolisttry2;

import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author anime
 */
public class AddTaskForm extends javax.swing.JFrame {

    MainController mainContr;
    DateFormat format;
    JXDatePicker picker;
    /**
     * Creates new form AddTaskForm
     * @param mainContr
     */
    public AddTaskForm(MainController mainContr) {
        initComponents();
        
        this.format = new SimpleDateFormat("dd.MM.yyyy");
        this.picker = new JXDatePicker();
        this.picker.setDate(Calendar.getInstance().getTime());
        this.picker.setFormats(this.format);
        this.picker.setBounds(taskNameField.getX(), 160, taskNameField.getWidth(), 22);
        this.add(picker);
        
        this.mainContr = mainContr;
        
        this.setTitle("Добавление задачи");
        this.setLocation(200, 150);
        this.setVisible(true);
        
        addTaskButton.setFont(new Font("Arial", Font.BOLD, 12));    //установка шрифтов
        cancelFormButton.setFont(new Font("Arial", Font.BOLD, 12)); //установка шрифтов
        enterDataLabel.setFont(new Font("Arial", Font.BOLD, 12));  //установка шрифтов
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterDataLabel = new javax.swing.JLabel();
        taskNameField = new javax.swing.JTextField();
        addTaskButton = new javax.swing.JButton();
        cancelFormButton = new javax.swing.JButton();
        taskPriorityBox = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        priorityLabel = new javax.swing.JLabel();
        deadlineLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        enterDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterDataLabel.setText("Введите данные");

        taskNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        taskNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameFieldActionPerformed(evt);
            }
        });

        addTaskButton.setText("Принять");
        addTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskButtonActionPerformed(evt);
            }
        });

        cancelFormButton.setText("Закрыть");
        cancelFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFormButtonActionPerformed(evt);
            }
        });

        taskPriorityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Выберите приоритет", "Очень важно", "Средне важно", "Не оч важно" }));
        taskPriorityBox.setSelectedIndex(2);
        taskPriorityBox.setToolTipText("");

        nameLabel.setText("Имя");

        priorityLabel.setText("Приоритет");

        deadlineLabel.setText("Дедлайн");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTaskButton)
                .addGap(18, 18, 18)
                .addComponent(cancelFormButton)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deadlineLabel)
                    .addComponent(priorityLabel)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taskPriorityBox, 0, 160, Short.MAX_VALUE)
                    .addComponent(taskNameField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(enterDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taskPriorityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityLabel))
                .addGap(18, 18, 18)
                .addComponent(deadlineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelFormButton)
                    .addComponent(addTaskButton))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFormButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelFormButtonActionPerformed

    private void addTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskButtonActionPerformed
        String taskName;
        Date deadline;
        int priority;
        if(taskPriorityBox.getSelectedIndex() != 0 && !taskNameField.getText().isEmpty()) {
            if(picker.getDate().after(Calendar.getInstance().getTime())) {
                deadline = picker.getDate();
                priority = taskPriorityBox.getSelectedIndex();
                taskName = taskNameField.getText();
                
                mainContr.addTask(taskName, priority, deadline);
                
                this.dispose();
            } else {
                enterDataLabel.setText("Извините, вы уже упустили дедлайн");
            }
        } else {
            enterDataLabel.setText("Вы не указали приоритет или имя задачи!");
        }
    }//GEN-LAST:event_addTaskButtonActionPerformed

    private void taskNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskNameFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTaskButton;
    private javax.swing.JButton cancelFormButton;
    private javax.swing.JLabel deadlineLabel;
    private javax.swing.JLabel enterDataLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JTextField taskNameField;
    private javax.swing.JComboBox<String> taskPriorityBox;
    // End of variables declaration//GEN-END:variables
}
