/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.todolisttry2;

import java.awt.Font;

/**
 *
 * @author anime
 */
public class DeleteTaskForm extends javax.swing.JFrame {

    MainController mainContr;
    Task task;
    /**
     * Creates new form DeleteTaskForm
     * @param mainContr
     * @param task
     */
    public DeleteTaskForm(MainController mainContr, Task task) {
        initComponents();
        
        this.mainContr = mainContr;
        this.task = task;
        
        this.setTitle("Удаление задач");
        this.setLocation(200, 150);
        this.setSize(500, 200);
        this.setResizable(true);
        this.setVisible(true);
        
        if (task.isTask()){
            deleteLabel.setText("Мне точно надо удалить задачу \""+ task.getName() +"\" со всеми ее подзадачами?");
        } else {
            deleteLabel.setText("Мне точно надо удалить подзадачу \""+ task.getName() +"\"?");
        }
        
        closeFormButton.setFont(new Font("Arial", Font.BOLD, 12));             //установка шрифтов
        deleteTaskButton.setFont(new Font("Arial", Font.BOLD, 12));            //установка шрифтов
        deleteLabel.setFont(new Font("Arial", Font.BOLD, 12)); //установка шрифтов
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteLabel = new javax.swing.JLabel();
        deleteTaskButton = new javax.swing.JButton();
        closeFormButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 200));

        deleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteLabel.setText("Если видно этот текст - все плохо");

        deleteTaskButton.setText("Да");
        deleteTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskButtonActionPerformed(evt);
            }
        });

        closeFormButton.setText("Нет");
        closeFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(deleteTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(closeFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(deleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTaskButton)
                    .addComponent(closeFormButton))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskButtonActionPerformed
        if (task.isTask()) {
            mainContr.deleteTask(task.getName());
        } else {
            mainContr.deleteSubtask(task.getName());
        }
        
        this.dispose();
    }//GEN-LAST:event_deleteTaskButtonActionPerformed

    private void closeFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFormButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeFormButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeFormButton;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JButton deleteTaskButton;
    // End of variables declaration//GEN-END:variables
}
